#ddev-generated

ddev_version_constraint: '>=v1.23.0'
web_extra_daemons:
  - name: "queue-1"
    command: 'while true; do /usr/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3; sleep 1; done'
    directory: /var/www/html
